# H2 ? ?????? (?????? ????? ???? ?????????? ????????)
spring.datasource.url=jdbc:h2:file:./data/habitsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA ????? ??? ????????? ??????? ?? ????? Entity-???????
spring.jpa.hibernate.ddl-auto=update

# H2 ??????? (??? ???????, ???????? ? ???????? ?? /h2-console)
spring.h2.console.enabled=true

# ?????????? SQL ? ????? (??? ?????)
spring.jpa.show-sql=true