package org.example.storage;

import org.example.model.Habit;
import org.example.model.HabitDTO;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class SaveToDB implements Saveable{

    private Connection connection;

    public SaveToDB() throws SQLException {
        String queryHabits = """
                CREATE TABLE IF NOT EXISTS habits (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) UNIQUE NOT NULL
                );
                """;

        String queryChecks = """
                CREATE TABLE IF NOT EXISTS checkpoints (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      habit_id BIGINT NOT NULL,
                      check_date TIMESTAMP NOT NULL,
                      CONSTRAINT fk_habit FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE,
                      CONSTRAINT uk_habit_date UNIQUE (habit_id, check_date) -- <- ДОБАВЛЕНА ЭТА СТРОКА
                  );
                """;

        connection = getNewConnection();
        Statement statement = connection.createStatement();

        statement.execute(queryHabits);

        statement.execute(queryChecks);

        close();
    }


    @Override
    public void save(HashMap<String, HabitDTO> habits, String variable) {
        try {
            connection = getNewConnection();
            String sql = "INSERT INTO habits (name) VALUES (?) ON CONFLICT (name) DO NOTHING;";
            PreparedStatement insertHabs = connection.prepareStatement(sql);

            for (Map.Entry<String, HabitDTO> habit : habits.entrySet()) {
                insertHabs.setString(1, habit.getKey());
                insertHabs.executeUpdate();
            }

            String sql1 = "select * from habits";

            PreparedStatement selectHabs = connection.prepareStatement(sql1);

            ResultSet rs = selectHabs.executeQuery();

            String sql2 = "INSERT INTO checkpoints (habit_id, check_date) VALUES (?, ?) ON CONFLICT (habit_id, check_date) DO NOTHING;";

            PreparedStatement insertCheck = connection.prepareStatement(sql2);
            while(rs.next()){
                ArrayList<LocalDateTime> tmp = habits.get(rs.getString("name")).getDates();
                for(LocalDateTime time : tmp){
                    insertCheck.setLong(1, rs.getLong("id"));
                    insertCheck.setTimestamp(2, Timestamp.valueOf(time));
                    insertCheck.executeUpdate();
                }

            }
            close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }


    @Override
    public HashMap<String, Habit> load(String variable) {

        HashMap<String, Habit> result = new HashMap<>();

        String sql = "select * from habits";
        String sql1 = "select * from checkpoints";
        HashMap<Long, Habit> habits = new HashMap<>();
        try {
            connection = getNewConnection();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                Habit habit = new Habit(rs.getString("name"));
                habits.put(rs.getLong("id"), habit);
            }
            close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        try {
            connection = getNewConnection();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery(sql1);

            while (rs.next()) {

                habits.get(rs.getLong("habit_id")).getDates().add(rs.getTimestamp("check_date").toLocalDateTime());
            }
            close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        for (Map.Entry<Long, Habit> habitEntry : habits.entrySet()) {
            result.put(habitEntry.getValue().getName(), habitEntry.getValue());
        }

        return result;
    }

    private Connection getNewConnection() throws SQLException{
        String url ="jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "1";
        return DriverManager.getConnection(url, user, password);
    }

    private void close() throws SQLException {
        connection.close();
    }
}
